#!/bin/bash
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning hhhhh"
echo "welcome to session hhhh"
