#!/bin/bash
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
echo "hello and good morning"
echo "welcome to session"
